# Generated by Django 3.1.4 on 2021-01-10 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('head_office', models.CharField(max_length=100)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_vendor_name', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('office_address', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=16)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.client')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('team_leader', models.CharField(blank=True, max_length=100)),
                ('crt_date', models.DateField()),
                ('location', models.CharField(max_length=500)),
                ('sub_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.subvendor')),
            ],
        ),
        migrations.AddField(
            model_name='subvendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.vendor'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoter_id', models.CharField(max_length=100)),
                ('promoter_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=10)),
                ('date_of_joining', models.DateField(blank=True)),
                ('date_of_leaving', models.DateField(blank=True)),
                ('kyc_document_type', models.CharField(blank=True, choices=[('aadhaar', 'AADHAAR'), ('voter', 'Voter'), ('ration', 'Ration'), ('pan', 'PAN')], max_length=10)),
                ('kyc_document_number', models.CharField(blank=True, max_length=20)),
                ('wage', models.IntegerField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('name_on_account', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('emergency_number', models.CharField(blank=True, max_length=16)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.team')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_manday', models.CharField(default='0', max_length=10)),
                ('sale_manday', models.CharField(default='0', max_length=10)),
                ('date', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
        ),
    ]
